#!/bin/bash
#cmsswRel=/afs/cern.ch/work/j/jsalfeld/Princeton/forZCounting2018/CMSSW_9_4_4/src
cmsswRel=/afs/cern.ch/work/d/dwalter/CMSSW_9_2_8/src
cd $cmsswRel
source /cvmfs/cms.cern.ch/cmsset_default.sh
eval `scramv1 runtime -sh`
cd -

### Input ###

cmsDir=/eos/home-d/dwalter/www/ZCounting/CMS-2016G-PromptReco-v2-ZRateData/

atlasCSV=/afs/cern.ch/user/p/ponyisi/public/zlumi/atlas_2018.csv
refCSV=/afs/cern.ch/work/d/dwalter/CMSSW_9_2_8/src/ZCounting/Stuff/ByLs_2016_IsoMu24OrIsoTkMu24_pcc16PaperV2.csv

### Output ###

mkdir -p $cmsDir/ZCrossSectionMonitoring
mkdir -p ${cmsDir}/ZAndMuonEfficiencies
mkdir -p ${cmsDir}/ZAndMuonEfficiencies/ATLAS_CMS_Comparison

### Plotting ###

python Plotting/plot_Zrate_DataCMS.py --cms $cmsDir/csvFiles/Mergedeffcsvfile.csv --refLumi $refCSV --saveDir $cmsDir/ZCrossSectionMonitoring/

python Plotting/plot_ZEfficiency_DataCMS.py --cms $cmsDir/csvFiles/Mergedeffcsvfile.csv --saveDir $cmsDir/ZAndMuonEfficiencies/

python Plotting/makeZvsL.py --cms $cmsDir/csvFiles/Mergedcsvfile.csv --saveDir $cmsDir/ZCrossSectionMonitoring/ #| tee -a $cmsDir/ZCrossSectionMonitoring/README.txt

#python Plotting/plot_Zrate_Data_CMSvsATLAS.py --cms $cmsDir/csvFiles/Mergedcsvfile.csv --atlas $atlasCSV -s $cmsDir/ZCrossSectionMonitoring/
