#!/bin/bash
export PATH=$HOME/.local/bin:/afs/cern.ch/cms/lumi/brilconda-1.1.7/bin:$PATH

#2016
# brilcalc lumi --begin 272786 --end 284044 -b "STABLE BEAMS" --byls -o ~/FillByLs_2016.csv --hltpath="HLT_Iso*Mu24_v*" --normtag="pcc16PaperV2"
brilcalc lumi --begin 272786 --end 284044 -b "STABLE BEAMS" --byls -o ~/FillByLs_2016.csv --hltpath="HLT_Iso*Mu24_v*" --normtag=/cvmfs/cms-bril.cern.ch/cms-lumi-pog/Normtags/normtag_PHYSICS.json -u /fb -i /afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions16/13TeV/Legacy_2016/Cert_271036-284044_13TeV_Legacy2016_Collisions16_JSON.txt

#2017
brilcalc lumi --begin 297046 --end 306462 -b "STABLE BEAMS" --byls -o ~/FillByLs_2017.csv --hltpath="HLT_IsoMu27_v*" --normtag=/cvmfs/cms-bril.cern.ch/cms-lumi-pog/Normtags/normtag_PHYSICS.json -u /fb -i Cert_294927-306462_13TeV_PromptReco_Collisions17_JSON.txt

#2018:
brilcalc lumi --begin 315252 --end 325175 -b "STABLE BEAMS" --byls -o ~/FillByLs_2018.csv --hltpath="HLT_IsoMu24_v*" --normtag="hfoc18v5"

#2017 low PU
# lumi sections from https://github.com/MiT-HEP/MitEwk13TeV/blob/CMSSW_94X/Selection/Cert_306896-307082_13TeV_PromptReco_Collisions17_JSON_LowPU_lowPU.txt
brilcalc lumi --begin 306929 --end 307082 -b "STABLE BEAMS" --byls -o ~/FillByLs_2017_lowPU.csv --hltpath="HLT_HIMu17_v*" --normtag=/cvmfs/cms-bril.cern.ch/cms-lumi-pog/Normtags/normtag_PHYSICS.json -u /fb -i Cert_306896-307082_13TeV_PromptReco_Collisions17_JSON_LowPU_lowPU.txt

# 2022
brilcalc lumi --begin 355100 --end 356615 -b "STABLE BEAMS" --byls -u /fb \
--normtag=/eos/cms/store/group/comm_luminosity/ZCounting/2022/Normtags/normtag_BRIL_20220824.json \
-i /eos/user/c/cmsdqm/www/CAF/certification/Collisions22/Cert_Collisions2022_355100_356615_Golden.json \
-o /eos/cms/store/group/comm_luminosity/ZCounting/2022/brilcalcByLS/byLS_Collisions22_355100_356615_Golden_20220824.csv